name: Run selenium test

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'Choose browser'
        default: 'chrome'
        required: true
        type: string

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Adjust if your script needs a different version

    - name: Install dependencies
      run: npm install

    - name: Run Selenium test
      run: node test/brokenImages.js --browser ${{ github.event.inputs.browser }}
